[package]
name = "computer_graphics"
version = "0.0.1"
edition = "2024"
authors = ["DeZtrOiD"]

[dependencies]
ash = {version = "0.38.0"}
glfw = { version = "0.60.0", features = ["vulkan"] }
imgui = "0.12.0"
imgui-rs-vulkan-renderer = "1.16.0"
